MentalHealth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),  # Example view
    path('articles', views.article_list, name='article_list'),  # Example view
    path('article/<int:pk>/', views.article_detail, name='article_detail'),
    path('article/categories/', views.category_list, name='category_list'),
    path('category/<str:category_name>/', views.article_by_category, name='article_by_category'),
    path('feedback/',views.feedback, name='feedback'),
    path('feedback-confirm/',views.feed_confirm, name='feedback-confirm'),


    path('therapists/', views.therapist_list, name='therapist_list'),
    path('therapists/<int:therapist_id>/', views.therapist_detail, name='therapist_detail'),
    path('therapists/<int:therapist_id>/book/', views.book_therapist, name='book_therapist'),
    path('booking/confirmation/', views.booking_confirmation, name='booking_confirmation'),

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('pricing/', views.pricing_view, name='pricing'),
    # path('therapist/', views.therapist_view, name='therapist'),
    path('therapistform/', views.therapistform_view, name='therapistform'),
    path('passrecovery/', views.passrecovery_view, name='passrecovery'),
    path('about/', views.about_view, name='about'),

    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('therapist-dashboard/', views.therapist_dashboard, name='therapist_dashboard'),
    path('patient-dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('add_article/', views.add_article, name='add_article'),

    path('bookings_list/', views.bookings_list, name='bookings_list'),
    path('bookings/', views.view_bookings, name='view_bookings'),
    path('bookings/<int:booking_id>/confirm/', views.confirm_booking, name='confirm_booking'),
    path('bookings/<int:booking_id>/reject/', views.reject_booking, name='reject_booking'),
]

core/models.py
# core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.utils import timezone


class User(AbstractUser):
    PATIENT = 'Patient'
    THERAPIST = 'Therapist'

    ROLE_CHOICES = (
        (PATIENT, 'Patient'),
        (THERAPIST, 'Therapist'),
    )

    full_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    telephone = models.CharField(max_length=20)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=PATIENT)

    # Add any other fields you need

    def promote_to_therapist(self):
        if self.is_superuser:
            self.role = self.THERAPIST
            self.save()

    def __str__(self):
        return self.username
    

class Article(models.Model):
    DEPRESSION = 'Depression'
    ANXIETY = 'Anxiety'
    STRESS_MANAGEMENT = 'Stress Management'
    MINDFULNESS_MEDITATION = 'Mindfulness and Meditation'
    TRAUMATIC_DISORDER = 'Traumatic Disorder'

    CATEGORY_CHOICES = [
        (DEPRESSION, 'Depression'),
        (ANXIETY, 'Anxiety'),
        (STRESS_MANAGEMENT, 'Stress Management'),
        (MINDFULNESS_MEDITATION, 'Mindfulness and Meditation'),
        (TRAUMATIC_DISORDER, 'Traumatic Disorder'),
    ]

    title = models.CharField(max_length=255)
    content = models.TextField()
    image = models.ImageField(upload_to='article_images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=DEPRESSION)

    def __str__(self):
        return self.title

class Therapist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='therapists/')
    names = models.CharField(max_length=255)
    bio = models.TextField()
    telephone = models.CharField(max_length=15,help_text="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    email = models.EmailField()

    def __str__(self):
        return self.names



class Booking(models.Model):
    PENDING = 'Pending'
    ACCEPTED = 'Accepted'
    REJECTED = 'Rejected'

    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (ACCEPTED, 'Accepted'),
        (REJECTED, 'Rejected'),
    ]

    therapist = models.ForeignKey(Therapist, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=PENDING)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} booking with {self.therapist.names} on {self.date}"


class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feedback = models.TextField()
    date_submitted = models.DateTimeField(auto_now_add=True)

templates/therapist-dash/add_article.html
{% extends 'therapist-dash/the_base.html' %}
{% load widget_tweaks %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
       <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  a:link {
        text-decoration: none;
      }
    
  </style>
</head>
<h2 style="text-align:center; color:blue;">ADD ARTICLE</h2>
<form method="POST" enctype="multipart/form-data" autocomplete="off" style="margin:100px;margin-top: 0px;">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_title">Title</label>
      {% render_field form.title class="form-control" placeholder="Enter title" %}

      <label for="id_content">Content</label>
      {% render_field form.content class="form-control" placeholder="Enter content" %}

      <label for="id_image">Image</label>
      {% render_field form.image class="form-control" placeholder="Choose image" %}

      <label for="id_category">Category</label>
      {% render_field form.category class="form-control" %}
    </div>

    <button type="submit" class="btn btn-primary">ADD</button>
</form>
<br><br><br>
{% endblock content %}

templates/therapist-dash/bookings.html
{% extends 'therapist-dash/the_base.html' %}
{% load widget_tweaks %}
{% block content %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <style type="text/css">
        a:link {
            text-decoration: none;
        }

        .order-card {
            color: rgb(255, 255, 255);
        }

        .bg-c-blue {
            background: #04868f;
        }

        .bg-c-green {
            background:#4C51BF;
        }

        .bg-c-yellow {
            background: #F56565;
        }

        .bg-c-pink {
            background: #663a30;
        }

        .card {
            -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
            box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
            border: 1px solid black;
            margin-bottom: 30px;
            -webkit-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
        }

        .card .card-block {
            padding: 25px;
        }

        .order-card i {
            font-size: 26px;
        }

        .f-left {
            float: left;
        }

        .f-right {
            float: right;
        }

        header {
            left: 0px;
            right: 0px;
        }
    </style>
</head>

<br><br>

<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">
          <h6 class="panel-title">View Bookings</h6>
        </div>
        <table class="table table-hover" id="dev-table">
          <thead>
            <tr>
              <th>First Names</th>
              <th>Tephone</th>
              <th>Age</th>
              <th>Category</th>
              <th>Date</th>
              <th>Message</th>
              <th>Status</th>

            </tr>
          </thead>
          {% for booking in bookings %}
          <tr>
    
            <td>yannick {{booking.first_name}}</td>
            <td> 0874353{{booking.telephone}}</td>
            <td> 23{{booking.age}}</td>
            <td> group{{booking.category}}</td>
            <td>12/01/2024 {{booking.date}}</td>
            <td> i nedds help{{booking.message}}</td>
            <td> 
                <form method="post" action="{% url 'confirm_booking' booking.id %}">
                    {% csrf_token %}
                    <button type="submit" name="action" value="confirm" class="btn btn-success btn-sm">Confirm</button>
                </form>
                <form method="post" action="{% url 'reject_booking' booking.id %}">
                    {% csrf_token %}
                    <button type="submit" name="action" value="reject" class="btn btn-danger btn-sm">Reject</button>
                </form>
            </td>
            
            
          </tr>
          {% endfor %}
        </table>
      </div>
</div>

<br><br><br><br><br><br><br><br><br><br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>

{% endblock content %}

templates/therapist-dash/the_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
 

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    body {
      margin: 0;
      padding: 0;
      font-family: "Gill Sans", sans-serif;;
    }

    header {
      position: fixed;
      background: #22242A;
      padding: 20px;
      width: 100%;
      z-index: 1;
    }

    .left_area h3 {
      color: #fff;
      margin: 0px;
      text-transform: uppercase;
      font-size: 22px;
      font-weight: 900;
    }

    .left_area span {
      color: #19B3D3;
    }

    .logout_btn {
      padding: 5px;
      background: #19B3D3;
      text-decoration: none;
      float: right;
      margin-top: -30px;
      margin-right: 40px;
      border-radius: 2px;
      font-size: 15px;
      font-weight: 600;
      color: #fff;
      transition: 0.5s;

    }

    .logout_btn:hover {
      background: #0B87A6;
    }

    .sidebar {
      background: #2f323a;
      margin-top: 70px;
      padding-top: 30px;
      position: fixed;
      left: 0;
      width: 250px;
      height: 100%;
      transition: 0.5s;
      transition-property: left;
    }

    .sidebar .profile_image {
      width: 100px;
      height: 100px;
      border-radius: 100px;
      margin-bottom: 10px;
    }

    .sidebar h4 {
      color: #ccc;
      margin-top: 0;
      
    }

    .sidebar a {
      color: #fff;
      display: block;
      width: 100%;
      line-height: 60px;
      text-decoration: none;
      padding-left: 40px;
      box-sizing: border-box;
      transition: 0.5s;

    }

    .sidebar a:hover {
      background: #19B3D3;
    }

    .sidebar i {
      padding-right: 10px;
    }

    label #sidebar_btn {
      z-index: 1;
      color: #fff;
      position: fixed;
      cursor: pointer;
      left: 300px;
      font-size: 20px;
      margin: 5px 0;
      transition: 0.5s;
      transition-property: color;
    }

    label #sidebar_btn:hover {
      color: #19B3D3;
    }

    #check:checked~.sidebar {
      left: -190px;
    }

    #check:checked~.sidebar a span {
      display: none;
    }

    #check:checked~.sidebar a {
      font-size: 20px;
      margin-left: 170px;
      width: 80px;
    }

    .content {
      margin-left: 250px;
      background: url(background.png) no-repeat;
      background-position: center;
      background-size: cover;
      height: 100vh;
      transition: 0.5s;
    }

    #check:checked~.content {
      margin-left: 60px;
    }

    #check {
      display: none;
    }
  </style>


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">


</head>

<body>

  <input type="checkbox" id="check">
  <!--header area start-->
  <header>
    <label for="check">
      <i style="left: 200px;margin-top: 17px;"class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
      <h3>Mental Health</h3>
    </div>
    <div class="right_area">
      <a href="/logout" class="logout_btn">Logout</a>
    </div>
    <div class="right_area">
        <a href="/" class="logout_btn">back to home</a>
      </div>
  </header>
  <!--header area end-->
  <!--sidebar start-->
  <div class="sidebar">
    <center>

      <img src="{% static "image/teacher.png" %}" class="profile_image" alt="">
      <h4>{{request.user.first_name}}</h4>
      <h6 style="color: rgb(255, 255, 255);">( Therapist )</h6>

    </center>
    <a href="{% url 'therapist_dashboard' %}"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a>
    <a href="{% url 'add_article' %}"><i class="fas fa-pen"></i><span>Articles</span></a>
    <a href="{% url 'bookings_list' %}"><i class="fas fa-book"></i><span>Bookings</span></a>
    <a href="{% url 'bookings_list' %}"><i class="fas fa-user"></i><span>Patient</span></a>
    <a href="{% url 'bookings_list' %}"><i class="fas fa-question-circle"></i><span>Feedbacks</span></a>
  </div>
  <!--sidebar end-->


  <!--content start-->
  <div class="content">
    <br><br><br><br><br>
    {% block content %}

    {% endblock content %}

    <br><br><br>
    <footer>
        <div class="container">
            <p>&copy; {% now "Y" %} Mental Health. All rights reserved.</p>
        </div>
    </footer>
  </div>
  <!--content end-->
</body>
</html>

templates/therapist-dash/therapist_dashboard.html
{% extends 'therapist-dash/the_base.html' %}
{% load widget_tweaks %}
{% block content %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <style type="text/css">
        a:link {
            text-decoration: none;
        }

        .order-card {
            color: rgb(255, 255, 255);
        }

        .bg-c-blue {
            background: #04868f;
        }

        .bg-c-green {
            background:#4C51BF;
        }

        .bg-c-yellow {
            background: #F56565;
        }

        .bg-c-pink {
            background: #663a30;
        }

        .card {
            -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
            box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
            border: 1px solid black;
            margin-bottom: 30px;
            -webkit-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
        }

        .card .card-block {
            padding: 25px;
        }

        .order-card i {
            font-size: 26px;
        }

        .f-left {
            float: left;
        }

        .f-right {
            float: right;
        }

        header {
            left: 0px;
            right: 0px;
        }
    </style>
</head>

<br><br>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-3">
            <div class="card bg-c-green order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Total Bookings </h6>
                    <h2 class="text-right"><i class="fas fa-user-graduate f-left"></i><span>{{total_bookings}}</span></h2>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="card bg-c-blue order-card">
                <div class="card-block">
                    <h6 class="m-b-20">My Articles</h6>
                    <h2 class="text-right"><i class="fas fa-pen f-left"></i><span>{{total_articles}}</span></h2>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="card bg-c-yellow order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Total Patients</h6>
                    <h2 class="text-right"><i class="fas fa-book f-left"></i><span>{{total_patients}}</span></h2>
                </div>
            </div>
        </div>

        

        <div class="col-md-6 col-lg-3">
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Feedbacks</h6>
                    <h2 class="text-right"><i class="fas fa-question-circle f-left"></i><span>{{total_feedback}}</span></h2>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <div class="panel panel-primary">
        <div class="panel-heading">
          <h6 class="panel-title">View Articles</h6>
        </div>
        <table class="table table-hover" id="dev-table">
          <thead>
            <tr>
                <th>Title</th>
                <th>Content</th>
                <th>Category</th>
                <!-- Add more headers as needed -->
            </tr>
          </thead>
          <tbody>
            {% for article in articles %}
            <tr>
                <td>{{ article.title }}</td>
                <td>{{ article.content }}</td>
                <td>{{ article.get_category_display }}</td>
                <!-- Add more columns as needed -->
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
</div>

<br><br><br><br><br><br><br><br><br><br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>

{% endblock content %}